/**
 * Everyday + branded foods with typical label servings. Searched first so typing
 * works offline / when USDA is rate-limited. Macros are for one serving.
 *
 * Brand rows include `aliases` so “oikos” hits Dannon Oikos yogurts.
 */

export const COMMON_FOODS = [
  // —— eggs & breakfast ——
  { id: 'local-egg-large', name: 'Egg, large', brand: 'Generic', serving: '1 large', calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8, aliases: ['eggs'] },
  { id: 'local-egg-white', name: 'Egg white, large', brand: 'Generic', serving: '1 large', calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1 },
  { id: 'local-egg-scrambled', name: 'Eggs, scrambled', brand: 'Generic', serving: '2 large', calories: 182, protein: 12, carbs: 2, fat: 13 },
  { id: 'local-egg-whites-carton', name: 'Egg whites, liquid', brand: 'Generic', serving: '3 tbsp (46 g)', calories: 25, protein: 5, carbs: 0, fat: 0 },
  { id: 'local-bacon', name: 'Bacon, pan-fried', brand: 'Generic', serving: '2 slices', calories: 90, protein: 6, carbs: 0, fat: 7 },
  { id: 'local-sausage-link', name: 'Breakfast sausage link', brand: 'Generic', serving: '1 link', calories: 70, protein: 4, carbs: 0, fat: 6 },
  { id: 'local-pancake', name: 'Pancake, plain', brand: 'Generic', serving: '1 medium (4 in)', calories: 90, protein: 2.5, carbs: 14, fat: 2.5 },
  { id: 'local-waffle', name: 'Waffle, plain', brand: 'Generic', serving: '1 waffle', calories: 120, protein: 3, carbs: 16, fat: 5 },
  { id: 'local-french-toast', name: 'French toast', brand: 'Generic', serving: '1 slice', calories: 150, protein: 5, carbs: 17, fat: 7 },
  { id: 'local-hash-brown', name: 'Hash brown', brand: 'Generic', serving: '1 patty', calories: 140, protein: 2, carbs: 15, fat: 8 },

  // —— meat & fish ——
  { id: 'local-chicken-breast', name: 'Chicken breast, grilled', brand: 'Generic', serving: '4 oz cooked', calories: 185, protein: 35, carbs: 0, fat: 4 },
  { id: 'local-chicken-thigh', name: 'Chicken thigh, grilled', brand: 'Generic', serving: '4 oz cooked', calories: 230, protein: 28, carbs: 0, fat: 13 },
  { id: 'local-chicken-rotisserie', name: 'Rotisserie chicken, breast', brand: 'Generic', serving: '4 oz', calories: 190, protein: 32, carbs: 0, fat: 7 },
  { id: 'local-ground-beef-93', name: 'Ground beef, 93% lean, cooked', brand: 'Generic', serving: '4 oz', calories: 195, protein: 28, carbs: 0, fat: 9 },
  { id: 'local-ground-beef-85', name: 'Ground beef, 85% lean, cooked', brand: 'Generic', serving: '4 oz', calories: 240, protein: 26, carbs: 0, fat: 15 },
  { id: 'local-turkey-breast', name: 'Turkey breast, roasted', brand: 'Generic', serving: '4 oz', calories: 170, protein: 34, carbs: 0, fat: 2.5 },
  { id: 'local-turkey-ground', name: 'Ground turkey, 93% lean, cooked', brand: 'Generic', serving: '4 oz', calories: 190, protein: 28, carbs: 0, fat: 8 },
  { id: 'local-salmon', name: 'Salmon, Atlantic, cooked', brand: 'Generic', serving: '4 oz', calories: 235, protein: 25, carbs: 0, fat: 14 },
  { id: 'local-tuna-can', name: 'Tuna, canned in water', brand: 'Generic', serving: '1 can drained (5 oz)', calories: 120, protein: 28, carbs: 0, fat: 1 },
  { id: 'local-shrimp', name: 'Shrimp, cooked', brand: 'Generic', serving: '4 oz', calories: 120, protein: 23, carbs: 1, fat: 2 },
  { id: 'local-cod', name: 'Cod, baked', brand: 'Generic', serving: '4 oz', calories: 120, protein: 26, carbs: 0, fat: 1 },
  { id: 'local-tilapia', name: 'Tilapia, baked', brand: 'Generic', serving: '4 oz', calories: 145, protein: 30, carbs: 0, fat: 3 },
  { id: 'local-steak', name: 'Sirloin steak, grilled', brand: 'Generic', serving: '4 oz', calories: 240, protein: 30, carbs: 0, fat: 13 },
  { id: 'local-pork-chop', name: 'Pork chop, grilled', brand: 'Generic', serving: '4 oz', calories: 230, protein: 28, carbs: 0, fat: 13 },
  { id: 'local-ham', name: 'Ham, sliced', brand: 'Generic', serving: '2 oz', calories: 70, protein: 10, carbs: 1, fat: 2.5 },
  { id: 'local-deli-turkey', name: 'Deli turkey breast', brand: 'Generic', serving: '2 oz', calories: 60, protein: 12, carbs: 1, fat: 1 },
  { id: 'local-tofu', name: 'Tofu, firm', brand: 'Generic', serving: '4 oz', calories: 140, protein: 16, carbs: 3, fat: 8 },
  { id: 'local-tempeh', name: 'Tempeh', brand: 'Generic', serving: '3 oz', calories: 160, protein: 16, carbs: 8, fat: 9 },
  { id: 'local-protein-shake', name: 'Whey protein shake', brand: 'Generic', serving: '1 scoop (30 g)', calories: 120, protein: 24, carbs: 3, fat: 1.5 },

  // —— carbs ——
  { id: 'local-oats', name: 'Oatmeal, cooked', brand: 'Generic', serving: '1 cup', calories: 158, protein: 6, carbs: 27, fat: 3.2 },
  { id: 'local-oats-dry', name: 'Oats, dry', brand: 'Generic', serving: '1/2 cup dry', calories: 150, protein: 5, carbs: 27, fat: 3 },
  { id: 'local-rice-white', name: 'White rice, cooked', brand: 'Generic', serving: '1 cup', calories: 205, protein: 4.3, carbs: 45, fat: 0.4 },
  { id: 'local-rice-brown', name: 'Brown rice, cooked', brand: 'Generic', serving: '1 cup', calories: 215, protein: 5, carbs: 45, fat: 1.8 },
  { id: 'local-quinoa', name: 'Quinoa, cooked', brand: 'Generic', serving: '1 cup', calories: 222, protein: 8, carbs: 39, fat: 3.6 },
  { id: 'local-pasta', name: 'Pasta, cooked', brand: 'Generic', serving: '1 cup', calories: 220, protein: 8, carbs: 43, fat: 1.3 },
  { id: 'local-pasta-whole', name: 'Whole wheat pasta, cooked', brand: 'Generic', serving: '1 cup', calories: 175, protein: 7.5, carbs: 37, fat: 0.8 },
  { id: 'local-bread-wheat', name: 'Whole wheat bread', brand: 'Generic', serving: '1 slice', calories: 80, protein: 4, carbs: 14, fat: 1 },
  { id: 'local-bread-white', name: 'White bread', brand: 'Generic', serving: '1 slice', calories: 75, protein: 2.5, carbs: 14, fat: 1 },
  { id: 'local-bagel', name: 'Bagel', brand: 'Generic', serving: '1 medium', calories: 270, protein: 10, carbs: 53, fat: 1.5 },
  { id: 'local-english-muffin', name: 'English muffin', brand: 'Generic', serving: '1 muffin', calories: 130, protein: 5, carbs: 26, fat: 1 },
  { id: 'local-tortilla', name: 'Flour tortilla', brand: 'Generic', serving: '1 medium (8 in)', calories: 140, protein: 4, carbs: 24, fat: 3.5 },
  { id: 'local-tortilla-corn', name: 'Corn tortilla', brand: 'Generic', serving: '1 small', calories: 50, protein: 1, carbs: 11, fat: 0.5 },
  { id: 'local-potato', name: 'Baked potato', brand: 'Generic', serving: '1 medium', calories: 160, protein: 4, carbs: 37, fat: 0.2 },
  { id: 'local-sweet-potato', name: 'Sweet potato, baked', brand: 'Generic', serving: '1 medium', calories: 100, protein: 2, carbs: 23, fat: 0.2 },
  { id: 'local-couscous', name: 'Couscous, cooked', brand: 'Generic', serving: '1 cup', calories: 175, protein: 6, carbs: 36, fat: 0.3 },

  // —— fruit & veg ——
  { id: 'local-banana', name: 'Banana', brand: 'Generic', serving: '1 medium', calories: 105, protein: 1.3, carbs: 27, fat: 0.4 },
  { id: 'local-apple', name: 'Apple', brand: 'Generic', serving: '1 medium', calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
  { id: 'local-orange', name: 'Orange', brand: 'Generic', serving: '1 medium', calories: 62, protein: 1.2, carbs: 15, fat: 0.2 },
  { id: 'local-berries', name: 'Mixed berries', brand: 'Generic', serving: '1 cup', calories: 70, protein: 1, carbs: 17, fat: 0.5 },
  { id: 'local-strawberries', name: 'Strawberries', brand: 'Generic', serving: '1 cup', calories: 50, protein: 1, carbs: 12, fat: 0.5 },
  { id: 'local-blueberries', name: 'Blueberries', brand: 'Generic', serving: '1 cup', calories: 85, protein: 1.1, carbs: 21, fat: 0.5 },
  { id: 'local-raspberries', name: 'Raspberries', brand: 'Generic', serving: '1 cup', calories: 65, protein: 1.5, carbs: 15, fat: 0.8 },
  { id: 'local-avocado', name: 'Avocado', brand: 'Generic', serving: '1/2 fruit', calories: 120, protein: 1.5, carbs: 6, fat: 11 },
  { id: 'local-grapes', name: 'Grapes', brand: 'Generic', serving: '1 cup', calories: 104, protein: 1, carbs: 27, fat: 0.2 },
  { id: 'local-mango', name: 'Mango', brand: 'Generic', serving: '1 cup sliced', calories: 100, protein: 1.4, carbs: 25, fat: 0.6 },
  { id: 'local-pineapple', name: 'Pineapple', brand: 'Generic', serving: '1 cup chunks', calories: 80, protein: 0.9, carbs: 22, fat: 0.2 },
  { id: 'local-watermelon', name: 'Watermelon', brand: 'Generic', serving: '1 cup diced', calories: 45, protein: 0.9, carbs: 11, fat: 0.2 },
  { id: 'local-broccoli', name: 'Broccoli, cooked', brand: 'Generic', serving: '1 cup', calories: 55, protein: 4, carbs: 11, fat: 0.6 },
  { id: 'local-spinach', name: 'Spinach, raw', brand: 'Generic', serving: '2 cups', calories: 14, protein: 1.8, carbs: 2.2, fat: 0.2 },
  { id: 'local-salad', name: 'Mixed green salad', brand: 'Generic', serving: '2 cups', calories: 20, protein: 1.5, carbs: 4, fat: 0.2 },
  { id: 'local-carrot', name: 'Carrots, raw', brand: 'Generic', serving: '1 cup chopped', calories: 50, protein: 1.2, carbs: 12, fat: 0.3 },
  { id: 'local-cucumber', name: 'Cucumber', brand: 'Generic', serving: '1 cup sliced', calories: 16, protein: 0.7, carbs: 4, fat: 0.1 },
  { id: 'local-tomato', name: 'Tomato', brand: 'Generic', serving: '1 medium', calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2 },
  { id: 'local-bell-pepper', name: 'Bell pepper', brand: 'Generic', serving: '1 medium', calories: 30, protein: 1, carbs: 7, fat: 0.3 },
  { id: 'local-zucchini', name: 'Zucchini, cooked', brand: 'Generic', serving: '1 cup', calories: 25, protein: 2, carbs: 5, fat: 0.4 },
  { id: 'local-asparagus', name: 'Asparagus, cooked', brand: 'Generic', serving: '1 cup', calories: 40, protein: 4, carbs: 7, fat: 0.4 },
  { id: 'local-green-beans', name: 'Green beans, cooked', brand: 'Generic', serving: '1 cup', calories: 45, protein: 2.4, carbs: 10, fat: 0.4 },
  { id: 'local-corn', name: 'Corn, cooked', brand: 'Generic', serving: '1 cup', calories: 130, protein: 5, carbs: 30, fat: 1.5 },
  { id: 'local-peas', name: 'Peas, cooked', brand: 'Generic', serving: '1 cup', calories: 120, protein: 8, carbs: 21, fat: 0.5 },

  // —— dairy & yogurt (generic) ——
  { id: 'local-milk-2', name: 'Milk, 2%', brand: 'Generic', serving: '1 cup', calories: 122, protein: 8, carbs: 12, fat: 4.8 },
  { id: 'local-milk-skim', name: 'Milk, skim', brand: 'Generic', serving: '1 cup', calories: 83, protein: 8, carbs: 12, fat: 0.2 },
  { id: 'local-milk-whole', name: 'Milk, whole', brand: 'Generic', serving: '1 cup', calories: 149, protein: 8, carbs: 12, fat: 8 },
  { id: 'local-greek-yogurt', name: 'Greek yogurt, plain nonfat', brand: 'Generic', serving: '1 cup (170 g)', calories: 100, protein: 17, carbs: 6, fat: 0.7, aliases: ['yogurt'] },
  { id: 'local-greek-yogurt-2', name: 'Greek yogurt, plain 2%', brand: 'Generic', serving: '1 cup (170 g)', calories: 150, protein: 20, carbs: 8, fat: 4, aliases: ['yogurt'] },
  { id: 'local-yogurt', name: 'Yogurt, plain lowfat', brand: 'Generic', serving: '1 cup', calories: 150, protein: 13, carbs: 17, fat: 4 },
  { id: 'local-cottage-cheese', name: 'Cottage cheese, lowfat', brand: 'Generic', serving: '1/2 cup', calories: 90, protein: 13, carbs: 5, fat: 2.5 },
  { id: 'local-cottage-1', name: 'Cottage cheese, 1%', brand: 'Generic', serving: '1 cup', calories: 160, protein: 28, carbs: 6, fat: 2.3 },
  { id: 'local-cheese-cheddar', name: 'Cheddar cheese', brand: 'Generic', serving: '1 oz', calories: 115, protein: 7, carbs: 0.4, fat: 9.5 },
  { id: 'local-cheese-mozz', name: 'Mozzarella, part-skim', brand: 'Generic', serving: '1 oz', calories: 70, protein: 7, carbs: 1, fat: 4.5 },
  { id: 'local-cheese-string', name: 'String cheese', brand: 'Generic', serving: '1 stick', calories: 80, protein: 7, carbs: 1, fat: 5 },
  { id: 'local-cream-cheese', name: 'Cream cheese', brand: 'Generic', serving: '2 tbsp', calories: 100, protein: 2, carbs: 2, fat: 10 },
  { id: 'local-butter', name: 'Butter', brand: 'Generic', serving: '1 tbsp', calories: 102, protein: 0.1, carbs: 0, fat: 11.5 },
  { id: 'local-sour-cream', name: 'Sour cream', brand: 'Generic', serving: '2 tbsp', calories: 60, protein: 1, carbs: 1, fat: 5 },

  // —— Oikos / Dannon (branded — what people actually buy) ——
  { id: 'oikos-triple-zero-vanilla', name: 'Oikos Triple Zero Vanilla', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 90, protein: 15, carbs: 9, fat: 0, aliases: ['oikos', 'dannon oikos', 'oikos yogurt', 'triple zero'] },
  { id: 'oikos-triple-zero-strawberry', name: 'Oikos Triple Zero Strawberry', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 90, protein: 15, carbs: 9, fat: 0, aliases: ['oikos', 'dannon oikos', 'oikos yogurt', 'triple zero'] },
  { id: 'oikos-triple-zero-blueberry', name: 'Oikos Triple Zero Blueberry', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 90, protein: 15, carbs: 9, fat: 0, aliases: ['oikos', 'dannon oikos', 'triple zero'] },
  { id: 'oikos-triple-zero-mixed', name: 'Oikos Triple Zero Mixed Berry', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 90, protein: 15, carbs: 9, fat: 0, aliases: ['oikos', 'dannon oikos', 'triple zero'] },
  { id: 'oikos-pro-plain', name: 'Oikos Pro Plain', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 140, protein: 20, carbs: 5, fat: 3.5, aliases: ['oikos', 'oikos pro', 'dannon oikos'] },
  { id: 'oikos-pro-vanilla', name: 'Oikos Pro Vanilla', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 140, protein: 20, carbs: 8, fat: 3, aliases: ['oikos', 'oikos pro'] },
  { id: 'oikos-pro-strawberry', name: 'Oikos Pro Strawberry', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 140, protein: 20, carbs: 8, fat: 3, aliases: ['oikos', 'oikos pro'] },
  { id: 'oikos-pro-mixed-berry', name: 'Oikos Pro Mixed Berry', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 140, protein: 20, carbs: 8, fat: 3, aliases: ['oikos', 'oikos pro'] },
  { id: 'oikos-plain-nonfat', name: 'Oikos Plain Nonfat Greek Yogurt', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 80, protein: 15, carbs: 6, fat: 0, aliases: ['oikos', 'oikos yogurt', 'dannon oikos', 'greek yogurt'] },
  { id: 'oikos-vanilla', name: 'Oikos Vanilla Greek Yogurt', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 120, protein: 12, carbs: 15, fat: 2, aliases: ['oikos', 'oikos yogurt'] },
  { id: 'oikos-strawberry', name: 'Oikos Strawberry Greek Yogurt', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 120, protein: 12, carbs: 15, fat: 2, aliases: ['oikos', 'oikos yogurt'] },
  { id: 'oikos-blueberry', name: 'Oikos Blueberry Greek Yogurt', brand: 'Oikos', serving: '1 container (5.3 oz)', calories: 120, protein: 12, carbs: 15, fat: 2, aliases: ['oikos', 'oikos yogurt'] },

  // —— other yogurt brands ——
  { id: 'chobani-plain-nonfat', name: 'Chobani Plain Nonfat Greek Yogurt', brand: 'Chobani', serving: '1 container (5.3 oz)', calories: 90, protein: 16, carbs: 6, fat: 0, aliases: ['chobani', 'greek yogurt'] },
  { id: 'chobani-vanilla', name: 'Chobani Vanilla Blended Greek Yogurt', brand: 'Chobani', serving: '1 container (5.3 oz)', calories: 130, protein: 12, carbs: 16, fat: 2.5, aliases: ['chobani'] },
  { id: 'chobani-strawberry', name: 'Chobani Strawberry Greek Yogurt', brand: 'Chobani', serving: '1 container (5.3 oz)', calories: 120, protein: 11, carbs: 15, fat: 0, aliases: ['chobani'] },
  { id: 'chobani-zero-vanilla', name: 'Chobani Zero Sugar Vanilla', brand: 'Chobani', serving: '1 container (5.3 oz)', calories: 60, protein: 12, carbs: 5, fat: 0, aliases: ['chobani', 'chobani zero'] },
  { id: 'fage-0', name: 'Fage Total 0% Plain', brand: 'Fage', serving: '1 cup (227 g)', calories: 130, protein: 23, carbs: 9, fat: 0, aliases: ['fage', 'greek yogurt'] },
  { id: 'fage-2', name: 'Fage Total 2% Plain', brand: 'Fage', serving: '1 cup (227 g)', calories: 170, protein: 20, carbs: 8, fat: 5, aliases: ['fage'] },
  { id: 'fage-5', name: 'Fage Total 5% Plain', brand: 'Fage', serving: '1 cup (227 g)', calories: 220, protein: 18, carbs: 6, fat: 12, aliases: ['fage'] },
  { id: 'two-good-strawberry', name: 'Two Good Strawberry', brand: 'Two Good', serving: '1 container (5.3 oz)', calories: 80, protein: 12, carbs: 3, fat: 2, aliases: ['two good', '2 good', 'yogurt'] },
  { id: 'two-good-plain', name: 'Two Good Plain', brand: 'Two Good', serving: '1 container (5.3 oz)', calories: 80, protein: 12, carbs: 3, fat: 2, aliases: ['two good', '2 good'] },
  { id: 'siggis-vanilla', name: "Siggi's Vanilla Skyr 0%", brand: "Siggi's", serving: '1 container (5.3 oz)', calories: 110, protein: 15, carbs: 12, fat: 0, aliases: ['siggi', 'siggis', 'skyr'] },
  { id: 'siggis-plain', name: "Siggi's Plain Skyr 0%", brand: "Siggi's", serving: '1 container (5.3 oz)', calories: 100, protein: 17, carbs: 7, fat: 0, aliases: ['siggi', 'siggis', 'skyr'] },
  { id: 'ratio-vanilla', name: 'Ratio Protein Vanilla', brand: 'Ratio', serving: '1 container (5.3 oz)', calories: 170, protein: 25, carbs: 7, fat: 4.5, aliases: ['ratio yogurt', 'ratio'] },
  { id: 'yoplait-original', name: 'Yoplait Original Strawberry', brand: 'Yoplait', serving: '1 container (6 oz)', calories: 150, protein: 6, carbs: 26, fat: 2, aliases: ['yoplait'] },
  { id: 'light-and-fit', name: 'Light + Fit Vanilla Greek Yogurt', brand: 'Dannon', serving: '1 container (5.3 oz)', calories: 80, protein: 12, carbs: 9, fat: 0, aliases: ['light and fit', 'light + fit'] },

  // —— milk brands ——
  { id: 'fairlife-2', name: 'Fairlife 2% Ultra-Filtered Milk', brand: 'Fairlife', serving: '1 cup (8 fl oz)', calories: 120, protein: 13, carbs: 6, fat: 4.5, aliases: ['fairlife', 'fair life'] },
  { id: 'fairlife-fatfree', name: 'Fairlife Fat Free Ultra-Filtered Milk', brand: 'Fairlife', serving: '1 cup (8 fl oz)', calories: 80, protein: 13, carbs: 6, fat: 0, aliases: ['fairlife'] },
  { id: 'fairlife-whole', name: 'Fairlife Whole Ultra-Filtered Milk', brand: 'Fairlife', serving: '1 cup (8 fl oz)', calories: 150, protein: 13, carbs: 6, fat: 8, aliases: ['fairlife'] },
  { id: 'fairlife-core-power', name: 'Core Power Protein Shake Chocolate', brand: 'Fairlife', serving: '1 bottle (14 fl oz)', calories: 170, protein: 26, carbs: 14, fat: 2.5, aliases: ['core power', 'fairlife'] },
  { id: 'almond-milk', name: 'Almond milk, unsweetened', brand: 'Generic', serving: '1 cup', calories: 30, protein: 1, carbs: 1, fat: 2.5 },
  { id: 'oat-milk', name: 'Oat milk', brand: 'Generic', serving: '1 cup', calories: 120, protein: 3, carbs: 16, fat: 5 },

  // —— bars & packaged ——
  { id: 'local-pb', name: 'Peanut butter', brand: 'Generic', serving: '2 tbsp', calories: 190, protein: 8, carbs: 7, fat: 16 },
  { id: 'local-almond-butter', name: 'Almond butter', brand: 'Generic', serving: '2 tbsp', calories: 190, protein: 7, carbs: 6, fat: 18 },
  { id: 'local-almonds', name: 'Almonds', brand: 'Generic', serving: '1 oz (23 nuts)', calories: 160, protein: 6, carbs: 6, fat: 14 },
  { id: 'local-peanuts', name: 'Peanuts, roasted', brand: 'Generic', serving: '1 oz', calories: 170, protein: 7, carbs: 5, fat: 14 },
  { id: 'local-cashews', name: 'Cashews', brand: 'Generic', serving: '1 oz', calories: 155, protein: 5, carbs: 9, fat: 12 },
  { id: 'local-olive-oil', name: 'Olive oil', brand: 'Generic', serving: '1 tbsp', calories: 120, protein: 0, carbs: 0, fat: 14 },
  { id: 'local-protein-bar', name: 'Protein bar', brand: 'Generic', serving: '1 bar', calories: 200, protein: 20, carbs: 22, fat: 6 },
  { id: 'quest-bar-cookies', name: 'Quest Bar Cookies & Cream', brand: 'Quest', serving: '1 bar', calories: 190, protein: 21, carbs: 21, fat: 8, aliases: ['quest', 'quest bar'] },
  { id: 'quest-bar-chocolate', name: 'Quest Bar Chocolate Chip Cookie Dough', brand: 'Quest', serving: '1 bar', calories: 190, protein: 21, carbs: 21, fat: 8, aliases: ['quest', 'quest bar'] },
  { id: 'rxbar-chocolate', name: 'RXBAR Chocolate Sea Salt', brand: 'RXBAR', serving: '1 bar', calories: 210, protein: 12, carbs: 23, fat: 9, aliases: ['rxbar', 'rx bar'] },
  { id: 'kind-bar', name: 'KIND Dark Chocolate Nuts & Sea Salt', brand: 'KIND', serving: '1 bar', calories: 200, protein: 6, carbs: 16, fat: 15, aliases: ['kind bar', 'kind'] },
  { id: 'clif-bar', name: 'Clif Bar Chocolate Chip', brand: 'Clif', serving: '1 bar', calories: 250, protein: 9, carbs: 44, fat: 6, aliases: ['clif', 'cliff bar'] },
  { id: 'premier-chocolate', name: 'Premier Protein Chocolate Shake', brand: 'Premier Protein', serving: '1 shake (11 fl oz)', calories: 160, protein: 30, carbs: 4, fat: 3, aliases: ['premier protein', 'premier'] },
  { id: 'premier-vanilla', name: 'Premier Protein Vanilla Shake', brand: 'Premier Protein', serving: '1 shake (11 fl oz)', calories: 160, protein: 30, carbs: 4, fat: 3, aliases: ['premier protein', 'premier'] },

  // —— bread brands ——
  { id: 'dkb-21', name: "Dave's Killer Bread 21 Whole Grains", brand: "Dave's Killer Bread", serving: '1 slice', calories: 110, protein: 5, carbs: 22, fat: 1.5, aliases: ['daves killer', "dave's killer bread", 'dkb'] },
  { id: 'dkb-powerseed', name: "Dave's Killer Bread Powerseed", brand: "Dave's Killer Bread", serving: '1 slice', calories: 100, protein: 5, carbs: 18, fat: 2.5, aliases: ['daves killer', 'dkb', 'powerseed'] },
  { id: 'mission-carb-balance', name: 'Mission Carb Balance Tortilla', brand: 'Mission', serving: '1 tortilla', calories: 70, protein: 6, carbs: 19, fat: 3.5, aliases: ['mission', 'carb balance', 'tortilla'] },
  { id: 'egglife', name: 'Egglife Egg White Wrap', brand: 'Egglife', serving: '1 wrap', calories: 30, protein: 5, carbs: 1, fat: 0, aliases: ['egglife', 'egg wrap'] },

  // —— drinks ——
  { id: 'local-coffee-black', name: 'Coffee, black', brand: 'Generic', serving: '1 cup', calories: 2, protein: 0.3, carbs: 0, fat: 0 },
  { id: 'local-coffee-latte', name: 'Latte, whole milk', brand: 'Generic', serving: '12 fl oz', calories: 180, protein: 9, carbs: 14, fat: 9 },
  { id: 'local-orange-juice', name: 'Orange juice', brand: 'Generic', serving: '1 cup', calories: 110, protein: 1.7, carbs: 26, fat: 0.3 },
  { id: 'local-soda', name: 'Cola soda', brand: 'Generic', serving: '12 fl oz', calories: 140, protein: 0, carbs: 39, fat: 0 },
  { id: 'local-diet-soda', name: 'Diet cola', brand: 'Generic', serving: '12 fl oz', calories: 0, protein: 0, carbs: 0, fat: 0 },
  { id: 'local-beer', name: 'Beer', brand: 'Generic', serving: '12 fl oz', calories: 150, protein: 1.6, carbs: 13, fat: 0 },
  { id: 'local-wine', name: 'Red wine', brand: 'Generic', serving: '5 fl oz', calories: 125, protein: 0.1, carbs: 4, fat: 0 },
  { id: 'local-gatorade', name: 'Sports drink', brand: 'Generic', serving: '12 fl oz', calories: 80, protein: 0, carbs: 21, fat: 0 },

  // —— meals / fast food ——
  { id: 'local-pizza-slice', name: 'Pizza, cheese', brand: 'Generic', serving: '1 slice', calories: 285, protein: 12, carbs: 36, fat: 10 },
  { id: 'local-burger', name: 'Hamburger, with bun', brand: 'Generic', serving: '1 sandwich', calories: 540, protein: 34, carbs: 40, fat: 27 },
  { id: 'local-cheeseburger', name: 'Cheeseburger', brand: 'Generic', serving: '1 sandwich', calories: 580, protein: 35, carbs: 40, fat: 31 },
  { id: 'local-fries', name: 'French fries', brand: 'Generic', serving: 'medium', calories: 340, protein: 4, carbs: 45, fat: 16 },
  { id: 'local-burrito', name: 'Bean and cheese burrito', brand: 'Generic', serving: '1 burrito', calories: 430, protein: 16, carbs: 58, fat: 15 },
  { id: 'local-sushi-roll', name: 'Sushi roll, California', brand: 'Generic', serving: '6 pieces', calories: 255, protein: 9, carbs: 38, fat: 7 },
  { id: 'local-ramen', name: 'Ramen noodles, packaged', brand: 'Generic', serving: '1 package cooked', calories: 380, protein: 8, carbs: 52, fat: 14 },
  { id: 'local-mac-cheese', name: 'Macaroni and cheese', brand: 'Generic', serving: '1 cup', calories: 310, protein: 12, carbs: 35, fat: 13 },
  { id: 'local-grilled-cheese', name: 'Grilled cheese sandwich', brand: 'Generic', serving: '1 sandwich', calories: 400, protein: 14, carbs: 30, fat: 25 },
  { id: 'local-pbj', name: 'Peanut butter & jelly sandwich', brand: 'Generic', serving: '1 sandwich', calories: 380, protein: 13, carbs: 48, fat: 16 },
  { id: 'local-chicken-nuggets', name: 'Chicken nuggets', brand: 'Generic', serving: '6 pieces', calories: 280, protein: 14, carbs: 16, fat: 18 },
  { id: 'local-hot-dog', name: 'Hot dog with bun', brand: 'Generic', serving: '1 hot dog', calories: 290, protein: 10, carbs: 24, fat: 17 },
  { id: 'local-taco', name: 'Hard taco, beef', brand: 'Generic', serving: '1 taco', calories: 180, protein: 9, carbs: 13, fat: 10 },

  // —— Del Taco (official nutrition list, mid-2026) ——
  // Macros: calories / protein / carbs / fat per menu item. Aliases so “del taco”
  // and “deltaco” hit this brand before USDA/Open Food Facts.
  { id: 'dt-del-taco-crunchy', name: 'The Del Taco (Crunchy)', brand: 'Del Taco', serving: '1 taco', calories: 300, protein: 16, carbs: 14, fat: 20, aliases: ['del taco', 'deltaco', 'crunchy taco', 'hard taco'] },
  { id: 'dt-del-taco-soft', name: 'The Del Taco (Soft)', brand: 'Del Taco', serving: '1 taco', calories: 290, protein: 17, carbs: 16, fat: 17, aliases: ['del taco', 'deltaco', 'soft taco'] },
  { id: 'dt-grilled-chicken-taco', name: 'Grilled Chicken Taco', brand: 'Del Taco', serving: '1 taco', calories: 210, protein: 11, carbs: 15, fat: 12, aliases: ['del taco', 'deltaco', 'chicken taco'] },
  { id: 'dt-chipotle-crispy-chicken-taco', name: 'Chipotle Crispy Chicken Taco', brand: 'Del Taco', serving: '1 taco', calories: 240, protein: 9, carbs: 22, fat: 12, aliases: ['del taco', 'deltaco', 'crispy chicken taco'] },
  { id: 'dt-ranch-crispy-chicken-taco', name: 'Ranch Crispy Chicken Taco', brand: 'Del Taco', serving: '1 taco', calories: 240, protein: 9, carbs: 22, fat: 12, aliases: ['del taco', 'deltaco', 'crispy chicken taco'] },
  { id: 'dt-beer-battered-fish-taco', name: 'Beer Battered Fish Taco', brand: 'Del Taco', serving: '1 taco', calories: 230, protein: 11, carbs: 28, fat: 9, aliases: ['del taco', 'deltaco', 'fish taco'] },
  { id: 'dt-carne-asada-street-taco', name: 'Carne Asada Steak Street Taco', brand: 'Del Taco', serving: '1 taco', calories: 120, protein: 10, carbs: 14, fat: 3.5, aliases: ['del taco', 'deltaco', 'street taco', 'carne asada taco'] },
  { id: 'dt-carne-asada-street-guac', name: "Carne Asada Steak Street Guac'd Up Taco", brand: 'Del Taco', serving: '1 taco', calories: 140, protein: 10, carbs: 15, fat: 4.5, aliases: ['del taco', 'deltaco', 'street taco', 'guac taco'] },
  { id: 'dt-carnitas-street-taco', name: 'Carnitas Street Taco', brand: 'Del Taco', serving: '1 taco', calories: 150, protein: 11, carbs: 12, fat: 7, aliases: ['del taco', 'deltaco', 'street taco', 'carnitas taco'] },
  { id: 'dt-grilled-chicken-street-taco', name: 'Grilled Chicken Street Taco', brand: 'Del Taco', serving: '1 taco', calories: 110, protein: 9, carbs: 13, fat: 3.5, aliases: ['del taco', 'deltaco', 'street taco', 'chicken taco'] },
  { id: 'dt-seasoned-beef-big-fat', name: 'Seasoned Beef Big Fat Taco', brand: 'Del Taco', serving: '1 taco', calories: 320, protein: 17, carbs: 31, fat: 15, aliases: ['del taco', 'deltaco', 'big fat taco', 'beef taco'] },
  { id: 'dt-grilled-chicken-big-fat', name: 'Grilled Chicken Big Fat Taco', brand: 'Del Taco', serving: '1 taco', calories: 340, protein: 16, carbs: 30, fat: 18, aliases: ['del taco', 'deltaco', 'big fat taco', 'chicken taco'] },
  { id: 'dt-carne-asada-big-fat', name: 'Carne Asada Steak Big Fat Taco', brand: 'Del Taco', serving: '1 taco', calories: 380, protein: 18, carbs: 30, fat: 21, aliases: ['del taco', 'deltaco', 'big fat taco', 'carne asada'] },
  { id: 'dt-carnitas-big-fat', name: 'Carnitas Big Fat Taco', brand: 'Del Taco', serving: '1 taco', calories: 410, protein: 19, carbs: 28, fat: 25, aliases: ['del taco', 'deltaco', 'big fat taco', 'carnitas'] },
  { id: 'dt-crispy-chicken-big-fat', name: 'Crispy Chicken Big Fat Taco', brand: 'Del Taco', serving: '1 taco', calories: 440, protein: 22, carbs: 39, fat: 23, aliases: ['del taco', 'deltaco', 'big fat taco', 'crispy chicken'] },
  { id: 'dt-snack-taco-crunchy', name: 'Snack Taco (Crunchy)', brand: 'Del Taco', serving: '1 taco', calories: 120, protein: 6, carbs: 8, fat: 7, aliases: ['del taco', 'deltaco', 'snack taco'] },
  { id: 'dt-snack-taco-soft', name: 'Snack Taco (Soft)', brand: 'Del Taco', serving: '1 taco', calories: 150, protein: 7, carbs: 14, fat: 6, aliases: ['del taco', 'deltaco', 'snack taco'] },
  { id: 'dt-bean-cheese-burrito-red', name: 'Bean & Cheese Burrito (Red)', brand: 'Del Taco', serving: '1 burrito', calories: 520, protein: 24, carbs: 79, fat: 10, aliases: ['del taco', 'deltaco', 'bean and cheese burrito', 'bean burrito'] },
  { id: 'dt-bean-cheese-burrito-green', name: 'Bean & Cheese Burrito (Green)', brand: 'Del Taco', serving: '1 burrito', calories: 500, protein: 24, carbs: 80, fat: 10, aliases: ['del taco', 'deltaco', 'bean and cheese burrito', 'bean burrito'] },
  { id: 'dt-value-bean-cheese-red', name: 'Value Bean & Cheese Burrito (Red)', brand: 'Del Taco', serving: '1 burrito', calories: 300, protein: 13, carbs: 43, fat: 8, aliases: ['del taco', 'deltaco', 'value burrito', 'bean burrito'] },
  { id: 'dt-value-bean-cheese-green', name: 'Value Bean & Cheese Burrito (Green)', brand: 'Del Taco', serving: '1 burrito', calories: 300, protein: 13, carbs: 44, fat: 8, aliases: ['del taco', 'deltaco', 'value burrito', 'bean burrito'] },
  { id: 'dt-del-combo-burrito', name: 'Del Combo Burrito (Beef & Bean)', brand: 'Del Taco', serving: '1 burrito', calories: 510, protein: 25, carbs: 57, fat: 18, aliases: ['del taco', 'deltaco', 'combo burrito', 'beef and bean burrito'] },
  { id: 'dt-del-beef-burrito', name: 'Del Beef Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 520, protein: 28, carbs: 40, fat: 26, aliases: ['del taco', 'deltaco', 'beef burrito'] },
  { id: 'dt-classic-chicken-burrito', name: 'Del Classic Chicken Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 560, protein: 24, carbs: 40, fat: 34, aliases: ['del taco', 'deltaco', 'chicken burrito', 'grilled chicken burrito'] },
  { id: 'dt-spicy-chicken-burrito', name: 'Spicy Grilled Chicken Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 560, protein: 30, carbs: 69, fat: 18, aliases: ['del taco', 'deltaco', 'spicy chicken burrito'] },
  { id: 'dt-carnitas-combo-burrito', name: 'Carnitas Combo Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 500, protein: 29, carbs: 56, fat: 19, aliases: ['del taco', 'deltaco', 'carnitas burrito'] },
  { id: 'dt-8-layer-veggie', name: '8 Layer Veggie Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 540, protein: 18, carbs: 73, fat: 17, aliases: ['del taco', 'deltaco', 'veggie burrito', '8 layer'] },
  { id: 'dt-jackd-up-brc', name: 'JACK\'D UP Beans, Rice & Cheese Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 450, protein: 16, carbs: 70, fat: 12, aliases: ['del taco', 'deltaco', 'beans rice cheese'] },
  { id: 'dt-epic-chicken-guac', name: 'Epic Grilled Chicken Fresh Guacamole Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 740, protein: 39, carbs: 92, fat: 26, aliases: ['del taco', 'deltaco', 'epic burrito', 'guacamole burrito'] },
  { id: 'dt-epic-carne-guac', name: 'Epic Carne Asada Steak Fresh Guacamole Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 770, protein: 42, carbs: 94, fat: 26, aliases: ['del taco', 'deltaco', 'epic burrito', 'carne asada burrito'] },
  { id: 'dt-epic-combo', name: 'Epic Combo Beef & Bean Burrito', brand: 'Del Taco', serving: '1 burrito', calories: 880, protein: 42, carbs: 79, fat: 41, aliases: ['del taco', 'deltaco', 'epic burrito', 'epic combo'] },
  { id: 'dt-chicken-cheddar-quesadilla', name: 'Chicken Cheddar Quesadilla', brand: 'Del Taco', serving: '1 quesadilla', calories: 540, protein: 29, carbs: 36, fat: 30, aliases: ['del taco', 'deltaco', 'quesadilla', 'chicken quesadilla'] },
  { id: 'dt-cheddar-quesadilla', name: 'Cheddar Quesadilla', brand: 'Del Taco', serving: '1 quesadilla', calories: 480, protein: 22, carbs: 35, fat: 27, aliases: ['del taco', 'deltaco', 'quesadilla', 'cheese quesadilla'] },
  { id: 'dt-carnitas-quesadilla', name: 'Carnitas Cheddar Quesadilla', brand: 'Del Taco', serving: '1 quesadilla', calories: 610, protein: 36, carbs: 34, fat: 36, aliases: ['del taco', 'deltaco', 'quesadilla', 'carnitas quesadilla'] },
  { id: 'dt-chicken-snacker', name: 'Chicken Snacker', brand: 'Del Taco', serving: '1 snacker', calories: 190, protein: 13, carbs: 15, fat: 9, aliases: ['del taco', 'deltaco', 'snacker'] },
  { id: 'dt-chicken-cheddar-roller', name: 'Chicken Cheddar Roller (Original)', brand: 'Del Taco', serving: '1 roller', calories: 250, protein: 13, carbs: 30, fat: 9, aliases: ['del taco', 'deltaco', 'roller', 'chicken roller'] },
  { id: 'dt-crunchtada', name: 'Crunchtada Tostada', brand: 'Del Taco', serving: '1 tostada', calories: 350, protein: 13, carbs: 44, fat: 14, aliases: ['del taco', 'deltaco', 'crunchtada', 'tostada'] },
  { id: 'dt-bean-cheese-cup', name: 'Bean & Cheese Cup', brand: 'Del Taco', serving: '1 cup', calories: 300, protein: 17, carbs: 42, fat: 6, aliases: ['del taco', 'deltaco', 'bean cup'] },
  { id: 'dt-chips-guac', name: 'Chips & Fresh Guacamole', brand: 'Del Taco', serving: '1 regular', calories: 340, protein: 5, carbs: 36, fat: 22, aliases: ['del taco', 'deltaco', 'chips and guac', 'guacamole'] },
  { id: 'dt-chips-queso', name: 'Chips & Queso Dip', brand: 'Del Taco', serving: '1 regular', calories: 640, protein: 14, carbs: 59, fat: 40, aliases: ['del taco', 'deltaco', 'chips and queso', 'queso'] },
  { id: 'dt-fries-regular', name: 'Crinkle Cut Fries (Regular)', brand: 'Del Taco', serving: '1 regular', calories: 320, protein: 4, carbs: 34, fat: 19, aliases: ['del taco', 'deltaco', 'fries', 'crinkle fries'] },
  { id: 'dt-fries-large', name: 'Crinkle Cut Fries (Large)', brand: 'Del Taco', serving: '1 large', calories: 410, protein: 5, carbs: 43, fat: 25, aliases: ['del taco', 'deltaco', 'fries', 'crinkle fries'] },
  { id: 'dt-chili-cheddar-fries', name: 'Chili Cheddar Fries', brand: 'Del Taco', serving: '1 order', calories: 570, protein: 15, carbs: 42, fat: 35, aliases: ['del taco', 'deltaco', 'chili fries', 'chili cheese fries'] },
  { id: 'dt-queso-loaded-fries', name: 'Queso Loaded Fries', brand: 'Del Taco', serving: '1 order', calories: 660, protein: 21, carbs: 46, fat: 44, aliases: ['del taco', 'deltaco', 'queso fries', 'loaded fries'] },
  { id: 'dt-del-cheeseburger', name: 'Del Cheeseburger', brand: 'Del Taco', serving: '1 burger', calories: 470, protein: 17, carbs: 34, fat: 28, aliases: ['del taco', 'deltaco', 'cheeseburger', 'burger'] },
  { id: 'dt-double-del', name: 'Double Del Cheeseburger', brand: 'Del Taco', serving: '1 burger', calories: 690, protein: 30, carbs: 35, fat: 47, aliases: ['del taco', 'deltaco', 'double del', 'double cheeseburger'] },
  { id: 'dt-taco-salad-chicken', name: 'Taco Salad with Fresh Guac (Grilled Chicken)', brand: 'Del Taco', serving: '1 salad', calories: 420, protein: 26, carbs: 22, fat: 26, aliases: ['del taco', 'deltaco', 'taco salad', 'chicken salad'] },
  { id: 'dt-taco-salad-beef', name: 'Taco Salad with Fresh Guac (Seasoned Beef)', brand: 'Del Taco', serving: '1 salad', calories: 540, protein: 28, carbs: 23, fat: 34, aliases: ['del taco', 'deltaco', 'taco salad', 'beef salad'] },
  { id: 'dt-breakfast-burrito-bec', name: 'Breakfast Burrito (Bacon, Egg & Cheese)', brand: 'Del Taco', serving: '1 burrito', calories: 520, protein: 30, carbs: 36, fat: 26, aliases: ['del taco', 'deltaco', 'breakfast burrito', 'bacon egg cheese'] },
  { id: 'dt-breakfast-burrito-egg', name: 'Breakfast Burrito (Egg & Cheese)', brand: 'Del Taco', serving: '1 burrito', calories: 380, protein: 16, carbs: 35, fat: 16, aliases: ['del taco', 'deltaco', 'breakfast burrito'] },
  { id: 'dt-breakfast-burrito-carne', name: 'Breakfast Burrito (Carne Asada, Egg & Cheese)', brand: 'Del Taco', serving: '1 burrito', calories: 450, protein: 25, carbs: 38, fat: 19, aliases: ['del taco', 'deltaco', 'breakfast burrito', 'carne asada breakfast'] },
  { id: 'dt-breakfast-big-fat-bec', name: 'Breakfast Big Fat Taco (Bacon Egg & Cheese)', brand: 'Del Taco', serving: '1 taco', calories: 340, protein: 18, carbs: 29, fat: 18, aliases: ['del taco', 'deltaco', 'breakfast taco', 'big fat breakfast'] },
  { id: 'dt-hashbrown-sticks', name: 'Hashbrown Sticks (5 Pc.)', brand: 'Del Taco', serving: '5 pieces', calories: 230, protein: 0, carbs: 18, fat: 17, aliases: ['del taco', 'deltaco', 'hashbrown', 'hash browns'] },
];
