/**
 * Everyday foods with typical servings — searched first so typing works even
 * offline or when the USDA key is rate-limited. Macros are for one serving.
 */

export const COMMON_FOODS = [
  { id: 'local-egg-large', name: 'Egg, large', brand: 'Generic', serving: '1 large', calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8 },
  { id: 'local-egg-white', name: 'Egg white, large', brand: 'Generic', serving: '1 large', calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1 },
  { id: 'local-egg-scrambled', name: 'Eggs, scrambled', brand: 'Generic', serving: '2 large', calories: 182, protein: 12, carbs: 2, fat: 13 },
  { id: 'local-chicken-breast', name: 'Chicken breast, grilled', brand: 'Generic', serving: '4 oz cooked', calories: 185, protein: 35, carbs: 0, fat: 4 },
  { id: 'local-chicken-thigh', name: 'Chicken thigh, grilled', brand: 'Generic', serving: '4 oz cooked', calories: 230, protein: 28, carbs: 0, fat: 13 },
  { id: 'local-ground-beef-93', name: 'Ground beef, 93% lean, cooked', brand: 'Generic', serving: '4 oz', calories: 195, protein: 28, carbs: 0, fat: 9 },
  { id: 'local-turkey-breast', name: 'Turkey breast, roasted', brand: 'Generic', serving: '4 oz', calories: 170, protein: 34, carbs: 0, fat: 2.5 },
  { id: 'local-salmon', name: 'Salmon, Atlantic, cooked', brand: 'Generic', serving: '4 oz', calories: 235, protein: 25, carbs: 0, fat: 14 },
  { id: 'local-tuna-can', name: 'Tuna, canned in water', brand: 'Generic', serving: '1 can drained (5 oz)', calories: 120, protein: 28, carbs: 0, fat: 1 },
  { id: 'local-shrimp', name: 'Shrimp, cooked', brand: 'Generic', serving: '4 oz', calories: 120, protein: 23, carbs: 1, fat: 2 },
  { id: 'local-cod', name: 'Cod, baked', brand: 'Generic', serving: '4 oz', calories: 120, protein: 26, carbs: 0, fat: 1 },
  { id: 'local-steak', name: 'Sirloin steak, grilled', brand: 'Generic', serving: '4 oz', calories: 240, protein: 30, carbs: 0, fat: 13 },
  { id: 'local-pork-chop', name: 'Pork chop, grilled', brand: 'Generic', serving: '4 oz', calories: 230, protein: 28, carbs: 0, fat: 13 },
  { id: 'local-tofu', name: 'Tofu, firm', brand: 'Generic', serving: '4 oz', calories: 140, protein: 16, carbs: 3, fat: 8 },
  { id: 'local-protein-shake', name: 'Whey protein shake', brand: 'Generic', serving: '1 scoop (30 g)', calories: 120, protein: 24, carbs: 3, fat: 1.5 },

  { id: 'local-oats', name: 'Oatmeal, cooked', brand: 'Generic', serving: '1 cup', calories: 158, protein: 6, carbs: 27, fat: 3.2 },
  { id: 'local-oats-dry', name: 'Oats, dry', brand: 'Generic', serving: '1/2 cup dry', calories: 150, protein: 5, carbs: 27, fat: 3 },
  { id: 'local-rice-white', name: 'White rice, cooked', brand: 'Generic', serving: '1 cup', calories: 205, protein: 4.3, carbs: 45, fat: 0.4 },
  { id: 'local-rice-brown', name: 'Brown rice, cooked', brand: 'Generic', serving: '1 cup', calories: 215, protein: 5, carbs: 45, fat: 1.8 },
  { id: 'local-quinoa', name: 'Quinoa, cooked', brand: 'Generic', serving: '1 cup', calories: 222, protein: 8, carbs: 39, fat: 3.6 },
  { id: 'local-pasta', name: 'Pasta, cooked', brand: 'Generic', serving: '1 cup', calories: 220, protein: 8, carbs: 43, fat: 1.3 },
  { id: 'local-bread-wheat', name: 'Whole wheat bread', brand: 'Generic', serving: '1 slice', calories: 80, protein: 4, carbs: 14, fat: 1 },
  { id: 'local-bread-white', name: 'White bread', brand: 'Generic', serving: '1 slice', calories: 75, protein: 2.5, carbs: 14, fat: 1 },
  { id: 'local-bagel', name: 'Bagel', brand: 'Generic', serving: '1 medium', calories: 270, protein: 10, carbs: 53, fat: 1.5 },
  { id: 'local-tortilla', name: 'Flour tortilla', brand: 'Generic', serving: '1 medium (8 in)', calories: 140, protein: 4, carbs: 24, fat: 3.5 },
  { id: 'local-potato', name: 'Baked potato', brand: 'Generic', serving: '1 medium', calories: 160, protein: 4, carbs: 37, fat: 0.2 },
  { id: 'local-sweet-potato', name: 'Sweet potato, baked', brand: 'Generic', serving: '1 medium', calories: 100, protein: 2, carbs: 23, fat: 0.2 },

  { id: 'local-banana', name: 'Banana', brand: 'Generic', serving: '1 medium', calories: 105, protein: 1.3, carbs: 27, fat: 0.4 },
  { id: 'local-apple', name: 'Apple', brand: 'Generic', serving: '1 medium', calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
  { id: 'local-orange', name: 'Orange', brand: 'Generic', serving: '1 medium', calories: 62, protein: 1.2, carbs: 15, fat: 0.2 },
  { id: 'local-berries', name: 'Mixed berries', brand: 'Generic', serving: '1 cup', calories: 70, protein: 1, carbs: 17, fat: 0.5 },
  { id: 'local-strawberries', name: 'Strawberries', brand: 'Generic', serving: '1 cup', calories: 50, protein: 1, carbs: 12, fat: 0.5 },
  { id: 'local-blueberries', name: 'Blueberries', brand: 'Generic', serving: '1 cup', calories: 85, protein: 1.1, carbs: 21, fat: 0.5 },
  { id: 'local-avocado', name: 'Avocado', brand: 'Generic', serving: '1/2 fruit', calories: 120, protein: 1.5, carbs: 6, fat: 11 },
  { id: 'local-grapes', name: 'Grapes', brand: 'Generic', serving: '1 cup', calories: 104, protein: 1, carbs: 27, fat: 0.2 },

  { id: 'local-broccoli', name: 'Broccoli, cooked', brand: 'Generic', serving: '1 cup', calories: 55, protein: 4, carbs: 11, fat: 0.6 },
  { id: 'local-spinach', name: 'Spinach, raw', brand: 'Generic', serving: '2 cups', calories: 14, protein: 1.8, carbs: 2.2, fat: 0.2 },
  { id: 'local-salad', name: 'Mixed green salad', brand: 'Generic', serving: '2 cups', calories: 20, protein: 1.5, carbs: 4, fat: 0.2 },
  { id: 'local-carrot', name: 'Carrots, raw', brand: 'Generic', serving: '1 cup chopped', calories: 50, protein: 1.2, carbs: 12, fat: 0.3 },
  { id: 'local-cucumber', name: 'Cucumber', brand: 'Generic', serving: '1 cup sliced', calories: 16, protein: 0.7, carbs: 4, fat: 0.1 },
  { id: 'local-tomato', name: 'Tomato', brand: 'Generic', serving: '1 medium', calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2 },

  { id: 'local-milk-2', name: 'Milk, 2%', brand: 'Generic', serving: '1 cup', calories: 122, protein: 8, carbs: 12, fat: 4.8 },
  { id: 'local-milk-skim', name: 'Milk, skim', brand: 'Generic', serving: '1 cup', calories: 83, protein: 8, carbs: 12, fat: 0.2 },
  { id: 'local-milk-whole', name: 'Milk, whole', brand: 'Generic', serving: '1 cup', calories: 149, protein: 8, carbs: 12, fat: 8 },
  { id: 'local-greek-yogurt', name: 'Greek yogurt, plain nonfat', brand: 'Generic', serving: '1 cup (170 g)', calories: 100, protein: 17, carbs: 6, fat: 0.7 },
  { id: 'local-yogurt', name: 'Yogurt, plain lowfat', brand: 'Generic', serving: '1 cup', calories: 150, protein: 13, carbs: 17, fat: 4 },
  { id: 'local-cottage-cheese', name: 'Cottage cheese, lowfat', brand: 'Generic', serving: '1/2 cup', calories: 90, protein: 13, carbs: 5, fat: 2.5 },
  { id: 'local-cheese-cheddar', name: 'Cheddar cheese', brand: 'Generic', serving: '1 oz', calories: 115, protein: 7, carbs: 0.4, fat: 9.5 },
  { id: 'local-butter', name: 'Butter', brand: 'Generic', serving: '1 tbsp', calories: 102, protein: 0.1, carbs: 0, fat: 11.5 },

  { id: 'local-pb', name: 'Peanut butter', brand: 'Generic', serving: '2 tbsp', calories: 190, protein: 8, carbs: 7, fat: 16 },
  { id: 'local-almonds', name: 'Almonds', brand: 'Generic', serving: '1 oz (23 nuts)', calories: 160, protein: 6, carbs: 6, fat: 14 },
  { id: 'local-olive-oil', name: 'Olive oil', brand: 'Generic', serving: '1 tbsp', calories: 120, protein: 0, carbs: 0, fat: 14 },
  { id: 'local-protein-bar', name: 'Protein bar', brand: 'Generic', serving: '1 bar', calories: 200, protein: 20, carbs: 22, fat: 6 },

  { id: 'local-coffee-black', name: 'Coffee, black', brand: 'Generic', serving: '1 cup', calories: 2, protein: 0.3, carbs: 0, fat: 0 },
  { id: 'local-coffee-latte', name: 'Latte, whole milk', brand: 'Generic', serving: '12 fl oz', calories: 180, protein: 9, carbs: 14, fat: 9 },
  { id: 'local-orange-juice', name: 'Orange juice', brand: 'Generic', serving: '1 cup', calories: 110, protein: 1.7, carbs: 26, fat: 0.3 },
  { id: 'local-soda', name: 'Cola soda', brand: 'Generic', serving: '12 fl oz', calories: 140, protein: 0, carbs: 39, fat: 0 },
  { id: 'local-beer', name: 'Beer', brand: 'Generic', serving: '12 fl oz', calories: 150, protein: 1.6, carbs: 13, fat: 0 },
  { id: 'local-wine', name: 'Red wine', brand: 'Generic', serving: '5 fl oz', calories: 125, protein: 0.1, carbs: 4, fat: 0 },

  { id: 'local-pizza-slice', name: 'Pizza, cheese', brand: 'Generic', serving: '1 slice', calories: 285, protein: 12, carbs: 36, fat: 10 },
  { id: 'local-burger', name: 'Hamburger, with bun', brand: 'Generic', serving: '1 sandwich', calories: 540, protein: 34, carbs: 40, fat: 27 },
  { id: 'local-fries', name: 'French fries', brand: 'Generic', serving: 'medium', calories: 340, protein: 4, carbs: 45, fat: 16 },
  { id: 'local-burrito', name: 'Bean and cheese burrito', brand: 'Generic', serving: '1 burrito', calories: 430, protein: 16, carbs: 58, fat: 15 },
  { id: 'local-sushi-roll', name: 'Sushi roll, California', brand: 'Generic', serving: '6 pieces', calories: 255, protein: 9, carbs: 38, fat: 7 },
  { id: 'local-ramen', name: 'Ramen noodles, packaged', brand: 'Generic', serving: '1 package cooked', calories: 380, protein: 8, carbs: 52, fat: 14 },
];
